// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations {
  [DbContext(typeof(AppDbContext))]
  [Migration("20260722071833_InitialCreate")]
  partial class InitialCreate {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "8.0.0")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Domain.Entities.ResultRecord", b => {
        b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");

        b.Property<double>("AvgExecutionTime")
            .HasPrecision(18, 6)
            .HasColumnType("double precision");

        b.Property<double>("AvgValue").HasPrecision(18, 6).HasColumnType("double precision");

        b.Property<double>("DeltaTimeSeconds")
            .HasPrecision(18, 6)
            .HasColumnType("double precision");

        b.Property<string>("FileName")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("character varying(255)");

        b.Property<double>("MaxValue").HasPrecision(18, 6).HasColumnType("double precision");

        b.Property<double>("MedianValue").HasPrecision(18, 6).HasColumnType("double precision");

        b.Property<DateTime>("MinDate").HasColumnType("timestamp with time zone");

        b.Property<double>("MinValue").HasPrecision(18, 6).HasColumnType("double precision");

        b.Property<DateTime>("ProcessedAt").HasColumnType("timestamp with time zone");

        b.HasKey("Id");

        b.HasIndex("AvgExecutionTime");

        b.HasIndex("AvgValue");

        b.HasIndex("FileName").IsUnique();

        b.HasIndex("MinDate");

        b.ToTable("ResultRecords");
      });

      modelBuilder.Entity("Domain.Entities.ValueRecord", b => {
        b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");

        b.Property<DateTime>("Date").HasColumnType("timestamp with time zone");

        b.Property<double>("ExecutionTime").HasPrecision(18, 6).HasColumnType("double precision");

        b.Property<string>("FileName")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("character varying(255)");

        b.Property<double>("Value").HasPrecision(18, 6).HasColumnType("double precision");

        b.HasKey("Id");

        b.HasIndex("Date");

        b.HasIndex("FileName");

        b.ToTable("ValueRecords");
      });
#pragma warning restore 612, 618
    }
  }
}
